name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t simple-php-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag simple-php-app ${{ secrets.DOCKER_USERNAME }}/simple-php-app
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-php-app

      - name: Deploy to Docker
        run: docker run -d -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/simple-php-app
